### ISSUE TITLE
`SizeMixin` is broken

### ISSUE THREAD

**Issue by Coal0** [lawsie/guizero#131]
Probably an oversight somewhere, but tkinter doesn't expose common attributes as properties of the widgets, i.e. instead of `tk.Tk.width`, provides `tk.Tk.winfo_width()` (whoever thought that was a good idea, but alas). Someone fell for this while writing [the `SizeMixin` class](https://github.com/lawsie/guizero/blob/dev/guizero/tkmixins.py#L143):

```python
>>> import guizero as gz
>>> import tkinter as tk
>>> 
>>> class Widget(gz.tkmixins.SizeMixin):
...     def __init__(self):
...         self.tk = tk.Tk()
...
>>> w = Widget()
>>> w.width
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/guizero/tkmixins.py", line 97, in width
    return self.tk.width
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tkinter/__init__.py", line 2095, in __getattr__
    return getattr(self.tk, attr)
AttributeError: '_tkinter.tkapp' object has no attribute 'width'
```

**Comment by martinohanlon** [comment]
Thanks 

Closing as it will be fixed as part of #136
