### ISSUE TITLE
Reduce pillow version requirement to what's in Raspbian

### ISSUE THREAD

**Issue by bennuttall** [lawsie/guizero#251]
Currently, guizero brings in the latest version of pillow from piwheels and that wheel depends on libjpeg, so the user is presented with a nonsense error that doesn't make it obvious what to do to fix it. We're working on this problem in piwheels, but in this case it can be addressed here.

Raspbian has pillow 4.0.0 and it's pre-installed, so I'd suggest pinning your requirement to >=4, not 4.3.

**Comment by martinohanlon** [comment]
In 0.6

**Comment by martinohanlon** [comment]
@bennuttall a problem... In pillow 4.0.0 `ImageTk` is not available. I dont think it was released until 4.2.1.

What is the problem with pip installing pillow on Raspbian?

**Comment by bsimmo** [comment]
It's installed by the system (apt) isn't it?
So you'd never want to override with pip as all hell can let loose.
At least anytime I've done it.

**Comment by martinohanlon** [comment]
There is something weird going on here... I am going to try with a clean Raspbian Desktop (no recommended software) install.

**Comment by martinohanlon** [comment]
Right.... This is what I have found.

+ `sudo pip install guizero` fails to install guizero in Raspbian due to a lack of dependency, as per the issue (see output below) - while not ideal, guizero does not support Python 2.
+ `sudo pip3 install guizero` - completes successfully installing guizero and PIL 5.4.1 as the pre-requisite is > 4.3.0
+ if guizero has PIL > 4.0.0 as the pre-requisite, PIL is not updated as it already met, HOWEVER, the installation of PIL doesn't include `python-imaging-tk` and therefore guizero reverts to not using and the functions it enables.

I am going to leave the pre-requisite for guizero as 4.3.0. 

 
```
sudo pip install guizero
Collecting guizero
  Downloading https://files.pythonhosted.org/packages/a5/34/fc4d4fc838cc90a34f4884891753ea22d5ba863bae3986efb67fa801c8ce/guizero-0.5.4.tar.gz
Collecting pillow>=4.3.0 (from guizero)
  Downloading https://files.pythonhosted.org/packages/3c/7e/443be24431324bd34d22dd9d11cc845d995bcd3b500676bcf23142756975/Pillow-5.4.1.tar.gz (16.0MB)
    100% |████████████████████████████████| 16.0MB 18kB/s 
Building wheels for collected packages: guizero, pillow
  Running setup.py bdist_wheel for guizero ... done
  Stored in directory: /root/.cache/pip/wheels/b2/09/14/8e3b48c42d86809f2ba1709b4d8eb642e5dd8655e5b689b53b
  Running setup.py bdist_wheel for pillow ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-LFCKXn/pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpOlPH6lpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-armv7l-2.7
  creating build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/OleFileIO.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageQt.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/GifImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/PalmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/PcdImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/MicImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/XpmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/SgiImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/TiffTags.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ContainerIO.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/GbrImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/GimpPaletteFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/PpmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageDraw2.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/PSDraw.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/TiffImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/DdsImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/PngImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/EpsImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/FitsStubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImagePath.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageEnhance.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/Image.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/TarIO.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/PaletteFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/MspImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/__init__.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/FtexImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/_util.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/GdImageFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageTransform.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/PdfImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/PixarImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageShow.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageWin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/DcxImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/FpxImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/WmfImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageMorph.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/PcxImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageStat.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/WalImageFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/XbmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageTk.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/JpegPresets.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/WebPImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/IptcImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/_binary.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/features.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageChops.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/BdfFontFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageCms.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageColor.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageFont.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/FliImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageGrab.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/PyAccess.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/FontFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageDraw.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/_version.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/IcoImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageMath.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/SunImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageMode.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageOps.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImagePalette.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/CurImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/MpoImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/PcfFontFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/TgaImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageFilter.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImtImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/PdfParser.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/BlpImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/JpegImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/PsdImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageSequence.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/MpegImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/GimpGradientFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ExifTags.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/BmpImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/_tkinter_finder.py -> build/lib.linux-armv7l-2.7/PIL
  running egg_info
  writing src/Pillow.egg-info/PKG-INFO
  writing top-level names to src/Pillow.egg-info/top_level.txt
  writing dependency_links to src/Pillow.egg-info/dependency_links.txt
  reading manifest file 'src/Pillow.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.c'
  warning: no files found matching '*.h'
  warning: no files found matching '*.sh'
  no previously-included directories found matching 'docs/_static'
  warning: no previously-included files found matching '.appveyor.yml'
  warning: no previously-included files found matching '.coveragerc'
  warning: no previously-included files found matching '.codecov.yml'
  warning: no previously-included files found matching '.editorconfig'
  warning: no previously-included files found matching '.landscape.yaml'
  warning: no previously-included files found matching '.readthedocs.yml'
  warning: no previously-included files found matching '.travis'
  warning: no previously-included files found matching '.travis/*'
  warning: no previously-included files found matching 'tox.ini'
  warning: no previously-included files matching '.git*' found anywhere in distribution
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.so' found anywhere in distribution
  writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
  running build_ext
  
  
  The headers or library files could not be found for jpeg,
  a required dependency when compiling Pillow from source.
  
  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-LFCKXn/pillow/setup.py", line 812, in <module>
      raise RequiredDependencyException(msg)
  __main__.RequiredDependencyException:
  
  The headers or library files could not be found for jpeg,
  a required dependency when compiling Pillow from source.
  
  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html
  
  
  
  ----------------------------------------
  Failed building wheel for pillow
  Running setup.py clean for pillow
Successfully built guizero
Failed to build pillow
Installing collected packages: pillow, guizero
  Found existing installation: Pillow 4.0.0
    Not uninstalling pillow at /usr/lib/python2.7/dist-packages, outside environment /usr
  Running setup.py install for pillow ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-LFCKXn/pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-NAy5Vt-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-armv7l-2.7
    creating build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/OleFileIO.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/ImageQt.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/GifImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/PalmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/PcdImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/MicImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/XpmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/SgiImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/TiffTags.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/ContainerIO.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/GbrImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/GimpPaletteFile.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/PpmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/ImageDraw2.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/PSDraw.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/ImageFile.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/TiffImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/DdsImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/PngImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/EpsImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/FitsStubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/ImagePath.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/ImageEnhance.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/Image.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/TarIO.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/PaletteFile.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/MspImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/__init__.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/FtexImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/_util.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/GdImageFile.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/ImageTransform.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/PdfImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/PixarImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/ImImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/ImageShow.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/ImageWin.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/DcxImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/FpxImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/WmfImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/ImageMorph.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/PcxImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/ImageStat.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/WalImageFile.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/XbmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/ImageTk.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/JpegPresets.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/WebPImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/IptcImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/_binary.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/features.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/ImageChops.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/BdfFontFile.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/ImageCms.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/ImageColor.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/ImageFont.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/FliImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/ImageGrab.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/PyAccess.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/FontFile.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/ImageDraw.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/_version.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/IcoImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/ImageMath.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/SunImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/ImageMode.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/ImageOps.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/ImagePalette.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/CurImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/MpoImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/PcfFontFile.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/TgaImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/ImageFilter.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/ImtImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/PdfParser.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/BlpImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/JpegImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/PsdImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/ImageSequence.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/MpegImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/GimpGradientFile.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/ExifTags.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/BmpImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying src/PIL/_tkinter_finder.py -> build/lib.linux-armv7l-2.7/PIL
    running egg_info
    writing src/Pillow.egg-info/PKG-INFO
    writing top-level names to src/Pillow.egg-info/top_level.txt
    writing dependency_links to src/Pillow.egg-info/dependency_links.txt
    reading manifest file 'src/Pillow.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.c'
    warning: no files found matching '*.h'
    warning: no files found matching '*.sh'
    no previously-included directories found matching 'docs/_static'
    warning: no previously-included files found matching '.appveyor.yml'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.codecov.yml'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.landscape.yaml'
    warning: no previously-included files found matching '.readthedocs.yml'
    warning: no previously-included files found matching '.travis'
    warning: no previously-included files found matching '.travis/*'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
    running build_ext
    
    
    The headers or library files could not be found for jpeg,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-LFCKXn/pillow/setup.py", line 812, in <module>
        raise RequiredDependencyException(msg)
    __main__.RequiredDependencyException:
    
    The headers or library files could not be found for jpeg,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    
    
    ----------------------------------------
  Can't rollback pillow, nothing uninstalled.
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-LFCKXn/pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-NAy5Vt-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-LFCKXn/pillow/
```

```
sudo pip3 install guizero
Collecting guizero
  Downloading https://files.pythonhosted.org/packages/1e/55/812fc7731565560dd76d0586cb563ccf13236818c3df7faaee381d898507/guizero-0.5.4-py3-none-any.whl
Collecting pillow>=4.3.0 (from guizero)
  Downloading https://www.piwheels.org/simple/pillow/Pillow-5.4.1-cp35-cp35m-linux_armv7l.whl (1.1MB)
    100% |████████████████████████████████| 1.1MB 278kB/s 
Installing collected packages: pillow, guizero
  Found existing installation: Pillow 4.0.0
    Not uninstalling pillow at /usr/lib/python3/dist-packages, outside environment /usr
Successfully installed guizero-0.5.4 pillow-5.4.1
```

**Comment by bsimmo** [comment]
Is Pillow just for the pictures, as having to install it breaks just
dropping the module in?
For use on old setups.
I know my sons large senior school cannot install or update anything and
they are sat on Python3.2 in Windows7 iirc.

If it is just pictures, could it be made optional?
So detect if the requirement is not satisfied and disable that part of it.
(Maybe a warning message if the picture part is imported ?)
Or does it already do something like that?

Problem does go away with Raspbian Buster sometime later this year, w.r.t
the Pi.

**Comment by bsimmo** [comment]
That's ok, the first part is what I was talking about (not pip3).
Seems I missed that part..as you were (oops)
